# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'
 use_frameworks!
target 'CoreML in ARKit' do
pod 'GoogleAPIClientForREST/Calendar', '~> 1.2.1'
pod 'Google/SignIn', '~> 3.0.3'
end


